# Imports

In [1]:
import numpy as np
import pandas as pd
from scipy import stats,linalg,constants

## Practice 1

In [2]:
arr1 = np.array([12,3,4,5,6,7,8,9,10])
mean = arr1.mean()
std = arr1.std()
print("mean: ",mean,"std: ",std)
p_value = stats.ttest_1samp(arr1,popmean=1)
print(p_value)
# t_tests =

mean:  7.111111111111111 std:  2.7666443551086073
TtestResult(statistic=6.247580176717713, pvalue=0.00024635487728732537, df=8)

In [3]:
arr2 = np.array([[45,4,32],[4,23,6],[45,23,9]])
print("Determinent ",linalg.det(arr2))
print("\nInverse value",linalg.inv(arr2))
print("\nEigan value",linalg.eig(arr2))

Determinent  -26135.0

Inverse value [[-0.00264014 -0.02678401  0.02724316]
 [-0.00895351  0.03960207  0.00543333]
 [ 0.03608188  0.03271475 -0.03898986]]

Eigan value (array([ 71.08182201+0.j, -16.44274294+0.j,  22.36092093+0.j]), array([[-0.77594387, -0.4555633 ,  0.40628632],
       [-0.14126866, -0.08854555, -0.89676486],
       [-0.61477985,  0.88578878, -0.17534027]]))

In [4]:
print(constants.pi)
print(constants.yotta)    
print(constants.zetta)    
print(constants.exa)      
print(constants.peta)     
print(constants.tera)     
print(constants.giga)     
print(constants.mega)     
print(constants.kilo)     
print(constants.hecto)    
print(constants.deka)     
print(constants.deci)     
print(constants.centi)    
print(constants.milli)    
print(constants.micro)    
print(constants.nano)     
print(constants.pico)     
print(constants.femto)    
print(constants.atto)     
print(constants.zepto)

3.141592653589793
1e+24
1e+21
1e+18
1000000000000000.0
1000000000000.0
1000000000.0
1000000.0
1000.0
100.0
10.0
0.1
0.01
0.001
1e-06
1e-09
1e-12
1e-15
1e-18
1e-21

In [5]:
df = pd.read_csv('dataset.csv')
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [6]:
df['Billing Amount'].describe()

count    55500.000000
mean     25539.316097
std      14211.454431
min      -2008.492140
25%      13241.224652
50%      25538.069376
75%      37820.508436
max      52764.276736
Name: Billing Amount, dtype: float64

In [7]:
df['Billing Amount'].dropna(inplace=True)

In [8]:
df.drop_duplicates(inplace=True)
print(df.count())

Name                  54966
Age                   54966
Gender                54966
Blood Type            54966
Medical Condition     54966
Date of Admission     54966
Doctor                54966
Hospital              54966
Insurance Provider    54966
Billing Amount        54966
Room Number           54966
Admission Type        54966
Discharge Date        54966
Medication            54966
Test Results          54966
dtype: int64

In [13]:
df.sort_values('Blood Type').head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
27037,WiLLiaM gILbERt,47,Male,A+,Diabetes,2022-11-12,Cynthia Brown,"Richmond, Hess and Lee",Medicare,24426.134975,155,Emergency,2022-11-20,Aspirin,Abnormal
4947,RAChaeL joNeS,32,Female,A+,Asthma,2023-05-27,Anna Miller,Gonzales-Ramirez,UnitedHealthcare,44275.201363,291,Emergency,2023-06-26,Paracetamol,Inconclusive
50949,GREGORY STone,82,Female,A+,Obesity,2020-02-16,Scott Wilson,"Sanders Reyes, Webb and",Medicare,16552.246648,233,Urgent,2020-03-06,Lipitor,Abnormal
39524,BrittaNy fInlEy,77,Female,A+,Obesity,2019-09-11,Michael Martin,Sons Dean and,Medicare,44051.870080,155,Urgent,2019-09-25,Aspirin,Inconclusive
11009,tamMY HArrIs,68,Male,A+,Arthritis,2021-08-05,Veronica Green,Carson-Howard,Cigna,34993.134024,128,Urgent,2021-08-25,Aspirin,Abnormal

In [43]:
df[(df['Medical Condition']=='Diabetes') | (df['Medical Condition']=='Cancer')]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
6,edwArD EDWaRDs,21,Female,AB-,Diabetes,2020-11-03,Kelly Olson,Group Middleton,Medicare,19580.872345,389,Emergency,2020-11-15,Paracetamol,Inconclusive
7,CHrisTInA MARtinez,20,Female,A+,Cancer,2021-12-28,Suzanne Thomas,"Powell Robinson and Valdez,",Cigna,45820.462722,277,Emergency,2022-01-07,Paracetamol,Inconclusive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55456,DEBRa MIller,17,Male,AB-,Cancer,2021-07-29,Samantha Russell,Collier-Jordan,UnitedHealthcare,43230.028453,125,Urgent,2021-08-01,Ibuprofen,Abnormal
55479,mIcHAeL SanTiAgo,58,Female,B-,Cancer,2022-01-05,Andrea Fields,Berry-Nguyen,Medicare,45767.175201,299,Elective,2022-01-29,Ibuprofen,Normal
55480,LAurEn mills,33,Female,B-,Diabetes,2020-09-30,Mr. David Murray MD,"Riggs, King and Walls",Cigna,22375.523434,323,Emergency,2020-10-26,Aspirin,Abnormal
55483,kimbErlY RIchArDSoN,15,Male,A-,Diabetes,2022-06-27,Erik Jones,PLC Hill,Blue Cross,12239.838237,177,Elective,2022-07-05,Lipitor,Abnormal
55490,STepHAniE oliVer,82,Male,B-,Cancer,2022-01-10,Gary Leblanc,Group Lee,Cigna,17350.543524,381,Emergency,2022-01-21,Penicillin,Abnormal